version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      # explicitly set the default user and password (even if empty)
      CLICKHOUSE_USER:  default
      CLICKHOUSE_PASSWORD: "123"
      # (optional) create a database for your app on startup:
      CLICKHOUSE_DB:     my_app_db
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"    # ← enable init of DB & user on first start
    networks:
      main:
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      main:
    command: ["redis-server"]


  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-race
    container_name: go-app
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
    depends_on:
      - clickhouse
    restart: on-failure
    environment:
      CLICKHOUSE_HOST:     clickhouse
      CLICKHOUSE_PORT:     "9000"
      CLICKHOUSE_USER:     default
      CLICKHOUSE_PASSWORD: "123"
      CLICKHOUSE_DATABASE: my_app_db
      REDIS_URL: "redis:6379"
    ports:
      - "8081:8081"   # HTTP
    networks:
      main:

volumes:
  clickhouse_data:


networks:
  main:
    driver: bridge